version: "3"

services:
        db:
                image: mysql:8.0
                container_name: db_wp_template
                restart: unless-stopped
                env_file: example.env
                environment:
                        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
                        MYSQL_USER: $MYSQL_USER
                        MYSQL_PASSWORD: $MYSQL_PASSWORD
                        MYSQL_DATABASE: $DB_NAME
                ports:
                        - "42333:3306"
                volumes:
                        - dbdata:/var/lib/mysql
                command: '--default-authentication-plugin=mysql_native_password'
                networks:
                        - app-network

        wordpress:
                depends_on:
                        - db
#                image: wordpress:php8.2-fpm-alpine
                build:
                        context: ./
                        dockerfile: dockerfile
                container_name: wp_template
                restart: unless-stopped
                env_file: example.env
                hostname: tecniwell-test.com
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: $MYSQL_USER
                        WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
                        WORDPRESS_DB_NAME: $DB_NAME
                        XDEBUG_CONFIG: client_host=host.docker.internal
                        WORDPRESS_DEBUG: true

                extra_hosts:
                        - "host.docker.internal:host-gateway"
                volumes:
                        - ./src/wordpress:/var/www/html
                        - ./src/themes/new-theme:/var/www/html/wp-content/themes/new-theme
                networks:
                        - app-network

        webserver:
                depends_on:
                        - wordpress
                image: nginx:1.15.12-alpine
                container_name: webserver
                restart: unless-stopped
                ports:
                        - "80:80"
                volumes:
                        - ./src/wordpress:/var/www/html
                        - ./src/nginx-conf:/etc/nginx/conf.d
                networks:
                        - app-network

volumes:
        dbdata:

networks:
        app-network:
                driver: bridge